---
name: Pull Request
about: Create a pull request to contribute to the project
title: ""
body:
  - type: markdown
    attributes:
      value: |
        Thanks for submitting a pull request! Please fill out the following form carefully.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Provide a brief description of the changes introduced by this PR
      placeholder: Tell us what you changed...
    validations:
      required: true

  - type: checkboxes
    id: type-of-change
    attributes:
      label: Type of Change
      description: What type of change does your PR introduce?
      options:
        - label: 🐛 Bug fix (non-breaking change which fixes an issue)
        - label: 🚀 New feature (non-breaking change which adds functionality)
        - label: 💥 Breaking change (fix or feature that would cause existing functionality to not work as expected)
        - label: 📝 Documentation update
        - label: 🧹 Code refactor
        - label: ⚡ Performance improvements

  - type: input
    id: related-issues
    attributes:
      label: Related Issues
      description: Link any related issues here using #issue_number
      placeholder: "Closes #"

  - type: textarea
    id: testing
    attributes:
      label: Testing
      description: Describe the tests you've added or modified
      placeholder: |
        - [ ] Added/modified unit tests
        - [ ] Tested manually
        - [ ] All tests passing

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your changes
      placeholder: Paste your screenshots here...

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: My code follows the project's style guidelines
        - label: I have performed a self-review of my code
        - label: I have commented my code, particularly in hard-to-understand areas
        - label: I have made corresponding changes to the documentation
        - label: My changes generate no new warnings
        - label: I have added tests that prove my fix is effective or that my feature works
        - label: New and existing unit tests pass locally with my changes

  - type: textarea
    id: additional-notes
    attributes:
      label: Additional Notes
      description: Add any additional notes for reviewers
      placeholder: Any additional information that might be helpful... 