---
name: Feature Request
about: Suggest an idea for this project
title: "[FEATURE] "
labels: ["enhancement"]
assignees: ''
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature!

  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: A clear and concise description of what feature you'd like to see
      placeholder: Tell us about the feature you'd like...
    validations:
      required: true

  - type: textarea
    id: problem-statement
    attributes:
      label: Problem Statement
      description: Describe the problem this feature would solve
      placeholder: What problem does this feature address?
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: Describe how you envision this feature working
      placeholder: How should this feature work?
    validations:
      required: true

  - type: textarea
    id: alternative-solutions
    attributes:
      label: Alternative Solutions
      description: Describe any alternative solutions you've considered
      placeholder: What other approaches could work?

  - type: textarea
    id: implementation-ideas
    attributes:
      label: Implementation Ideas
      description: If you have any specific ideas about how to implement this feature
      placeholder: Share your technical thoughts...

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request here
      placeholder: Any additional information that might be helpful... 